import SiteHeader from "@/components/site-header";
import SiteFooter from "@/components/site-footer";

const products=[
{name:"Cosmic Dome",family:"Fabricated",type:"Decorative / Technical",image:"https://www.lunnark.com/assets/images/home/new-products/DS-42-Cosmic-Dome-1.png",path:"/product_info/products/all/Fabricated/Cosmic-Dome"},
{name:"Echodisk",family:"Acoustic",type:"Acoustic / Pendant",image:"https://www.lunnark.com/assets/images/home/new-products/AO19_Acous_Disk.png",path:"/product_info/products/all/Acoustic/Echodisk"},
{name:"Bubble",family:"Fabricated",type:"Fabricated / Floor",image:"https://www.lunnark.com/assets/images/home/new-products/DS-64-Bubble.png",path:"/product_info/products/all/Fabricated/Bubble"},
{name:"Conio",family:"Acoustic",type:"Acoustic / Suspended",image:"https://www.lunnark.com/assets/images/home/new-products/AO10_Acous_K.png",path:"/product_info/products/all/Acoustic/Conio"},
{name:"Band",family:"Acrylic",type:"Decorative",image:"https://www.lunnark.com/assets/images/home/new-products/DS-42-Cosmic-Dome-1.png",path:"/product_info/products/all/Acrylic/Band"},
{name:"Faber",family:"Fabric",type:"Decorative",image:"https://www.lunnark.com/assets/images/home/new-products/AO19_Acous_Disk.png",path:"/product_info/products/all/Fabric/Faber"},
{name:"Slide",family:"Wood",type:"Decorative",image:"https://www.lunnark.com/assets/images/home/new-products/AO10_Acous_K.png",path:"/product_info/products/all/Wood/Slide"},
{name:"Gear",family:"Fabricated",type:"Decorative",image:"https://www.lunnark.com/assets/images/home/new-products/DS-64-Bubble.png",path:"/product_info/products/all/Fabricated/Gear"},
{name:"Spino",family:"Spinned",type:"Decorative",image:"https://www.lunnark.com/assets/images/home/new-products/AO10_Acous_K.png",path:"/product_info/products/all/Spinned/Spino"},
{name:"Hazo",family:"Wood",type:"Decorative",image:"https://www.lunnark.com/assets/images/home/new-products/AO19_Acous_Disk.png",path:"/product_info/products/all/Wood/Hazo"},
{name:"Torc",family:"Wood",type:"Decorative",image:"https://www.lunnark.com/assets/images/home/new-products/DS-42-Cosmic-Dome-1.png",path:"/product_info/products/all/Wood/Torc"},
{name:"W",family:"Linear",type:"Functional",image:"https://www.lunnark.com/assets/images/home/new-products/AO10_Acous_K.png",path:"/product_info/products/all/Linear/W"},
{name:"Luma Line",family:"Magnetic Track Lights",type:"Functional",image:"https://www.lunnark.com/assets/images/home/new-products/AO19_Acous_Disk.png",path:"/product_info/products/all/Magnetic_Track_Lights/Luma-Line"},
{name:"Axis-Cyl",family:"Magnetic Track Lights",type:"Functional",image:"https://www.lunnark.com/assets/images/home/new-products/DS-64-Bubble.png",path:"/product_info/products/all/Magnetic_Track_Lights/Axis-Cyl"}
];

function Layout({title,children}:{title:string,children:React.ReactNode}){return <><SiteHeader/><main className="inner-page"><div className="inner-hero"><span>LUNNARK</span><h1>{title}</h1></div>{children}</main><SiteFooter/></>}
function Card({p}:{p:any}){return <a className="inner-product-card" href={p.path}><div className="inner-product-image"><img src={p.image} alt={p.name}/></div><small>{p.type}</small><h3>{p.name}</h3><span>View More →</span></a>}
function Products({cat="All Products"}){const list=cat==="All Products"?products:products.filter(p=>(p.type+" "+p.family).toLowerCase().includes(cat.toLowerCase()));return <Layout title={cat}><section className="content-section"><form className="site-search" action="/search"><input name="q" placeholder="Search Here for......"/><button>Search</button></form><div className="filter-tabs"><a href="/all">All</a><a href="/all/decorative">Decorative</a><a href="/all/functional">Functional</a><a href="/all/kinetic">Kinetic</a><a href="/all/mounting">Mounting</a></div><div className="inner-product-grid">{(list.length?list:products).map(p=><Card p={p} key={p.name}/>)}</div></section></Layout>}
function Product({p}:{p:any}){return <Layout title={p.name}><section className="product-detail"><div className="product-detail-image"><img src={p.image} alt={p.name}/></div><div className="product-detail-copy"><small>{p.family} / {p.type}</small><h2>{p.name}</h2><p>LunnArk luminaire designed for high-quality architectural lighting applications.</p><h3>Technical Specification</h3><div className="spec-grid">{[["Luminous Efficacy","Up to 95 Lm/W"],["Color Temperature","2700K / 3000K / 4000K / 5700K"],["CRI","≥80 Standard / ≥90 Optional"],["UGR","< 19"],["LED Life","> 50,000 hours"],["Control","Switch / DALI / Analog"]].map(x=><div key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div><a className="primary-btn" href="/contact_us">Enquire About This Product →</a></div></section></Layout>}

export default async function Page({params,searchParams}:{params:Promise<{slug?:string[]}>,searchParams:Promise<{q?:string}>}) {
const {slug=[]}=await params; const sp=await searchParams; const path="/"+slug.join("/");
if(path==="/all") return <Products/>; if(path==="/all/decorative") return <Products cat="Decorative"/>; if(path==="/all/functional") return <Products cat="Functional"/>; if(path==="/all/kinetic") return <Products cat="Kinetic"/>; if(path==="/all/mounting") return <Products cat="Mounting"/>;
if(path.startsWith("/product_info/products/")){const name=(slug.at(-1)||"").replace(/-/g," ").toLowerCase();return <Product p={products.find(x=>x.name.toLowerCase()===name)||products[0]}/>;}
if(path==="/search"){const q=sp.q||"";const found=products.filter(p=>(p.name+" "+p.family+" "+p.type).toLowerCase().includes(q.toLowerCase()));return <Layout title={"Search"+(q?" — "+q:"")}><section className="content-section"><form className="site-search" action="/search"><input name="q" defaultValue={q} placeholder="Search Here for......"/><button>Search</button></form><div className="inner-product-grid">{found.map(p=><Card p={p} key={p.name}/>)}</div></section></Layout>;}
if(path==="/projects") return <Layout title="Projects"><section className="content-section"><p className="lead">Explore our handpicked projects and find the perfect one that resonates with your vision.</p><div className="project-grid">{[["Walmart","Bengaluru and Chennai"],["Boeing India Private Limited","Chennai, India"],["Cognizant Technology Solutions India","Hyderabad, India"],["Wipro Technology","Gurugram, India"],["HSBC Software Development India","Pune, India"],["Wells Fargo","Bangalore, India"],["Phillips Prana","Bangalore, India"],["PES University","Bangalore, India"],["Kalyani Aura","Bengaluru, India"],["Microsoft","Hyderabad, India"],["Infosys","Bengaluru, India"]].map(x=><a className="project-card" href="/projects" key={x[0]}><small>PROJECT</small><h3>{x[0]}</h3><p>{x[1]}</p><span>View Project →</span></a>)}</div></section></Layout>;
if(path==="/bespoke") return <Layout title="Bespoke"><section className="prose-section"><h2>Where Creativity and Sustainability Illuminate Your World</h2><p>From prototyping to final installation, LunnArk creates tailored lighting solutions for unique spaces.</p><h2>Endless Custom Possibilities</h2><div className="feature-grid"><div><h3>Material Variety</h3><p>Metal, wood, glass and innovative composites.</p></div><div><h3>Color Temperature Flexibility</h3><p>Warm inviting tones through crisp cool illumination.</p></div><div><h3>Sensor and Smart Lighting</h3><p>Motion sensors, timers and IoT-enabled controls.</p></div><div><h3>Custom Placement</h3><p>Ceiling, wall, recessed, pendant and unique configurations.</p></div></div><a className="primary-btn" href="/contact_us">Start Your Customization Journey →</a></section></Layout>;
if(path==="/about") return <Layout title="About LunnArk"><section className="prose-section"><h2>LunnArk is a global lighting brand born in Bengaluru.</h2><p>LunnArk®, a pioneering brand by Vtech Biotron Private Limited, offers cutting-edge integrated LED lighting solutions distinguished by exceptional design and benchmark luminaire standards.</p><div className="stats-row"><div><b>20,000+</b><span>sq. ft. facility</span></div><div><b>10,000–1M</b><span>sq. ft. project capability</span></div><div><b>ISO / BIS</b><span>certification-led manufacturing</span></div></div><h2>Manufacturing Excellence</h2><p>Our Rajajinagar, Bengaluru facility brings together artistic designers, innovative thinkers and technically skilled engineers.</p><h2>Our Journey</h2><p>2006 established · 2011 LED business · 2014 innovations and export · 2019 elemental lighting · 2021 Cosmic Dome · 2022 acoustic range · 2023 patents · 2024 Kinetic DMX · 2025 continued innovation.</p></section></Layout>;
if(path==="/resources") return <Layout title="Resources"><section className="content-section"><div className="resource-grid"><div className="resource-card"><span>CATALOGUE</span><h2>Decorative Technical Catalogue</h2><p>Explore LunnArk luminaire design, projects and technical possibilities.</p><a href="https://www.lunnark.com/assets/images/downloads/decorative_technical.pdf">View Catalogue →</a></div><div className="resource-card"><span>BROCHURES 2024-25</span><h2>Product Brochures</h2><p>Qafasoul, Linea Light, Linio Curve, V-Tech Series and Magnetic Series.</p></div><div className="resource-card"><span>MAKE IN INDIA</span><h2>Made in India. Made by Indians.</h2><a href="/make_in_india">Explore →</a></div></div></section></Layout>;
if(path==="/make_in_india") return <Layout title="Make in India"><section className="prose-section"><h2>MADE IN INDIA. MADE BY INDIANS.</h2><p>LunnArk by Vtech Biotron Pvt Ltd manufactures its entire product line in Bangalore, creating jobs and supporting the local economy.</p><h2>Atmanirbhar Bharat</h2><p>Make in India is at the heart of LunnArk’s strategy through local sourcing, engineering, innovation, service and support.</p><h2>Developed Domestically to Enhance the Global Ecosystem</h2><p>Design, engineering and manufacturing are focused on high-quality and accessible luminaires from India for the world.</p></section></Layout>;
if(path==="/sustainability") return <Layout title="Sustainability"><section className="prose-section"><h2>Lighting a brighter, safer and greener future.</h2><div className="feature-grid"><div><h3>Efficient LED</h3><p>High-efficiency LED systems designed for controlled energy use.</p></div><div><h3>Smart Controls</h3><p>DALI, Bluetooth, sensors and control options.</p></div><div><h3>Local Manufacturing</h3><p>Design, engineering and manufacturing in India.</p></div><div><h3>Long Life</h3><p>Durable luminaires and long-life LED sources.</p></div></div></section></Layout>;
if(path==="/contact_us") return <Layout title="Contact Us"><section className="contact-page"><div><h2>Let's talk about your lighting project.</h2><p>1800 890 2146<br/>080 - 23507469</p><p>info@lunnark.com<br/>info@vtechbiotron.com<br/>sales@lunnark.com</p><p>#40, 3rd Floor, 2nd Main road, Rajajnagar Industrial Town, Magadi Main road, Bengaluru, Karnataka 560010</p></div><form className="enquiry-form"><input placeholder="Your Name*" required/><input type="email" placeholder="Your Email*" required/><input placeholder="Mobile*" required/><textarea placeholder="Tell us about your project" rows={6}/><button>Send Enquiry →</button></form></section></Layout>;
if(path==="/blogs") return <Layout title="Blogs"><section className="content-section"><p className="lead">Discover our blogs about lighting designs, creative ideas and unique solutions.</p><div className="blog-list">{[["04-09-2024","Ultimate Guide to Selecting the Ideal Light Fixtures"],["03-09-2024","Global Reach: How Our LED Solutions Are Shaping Industries Worldwide"],["02-09-2024","LED Lighting in Healthcare: Improving Patient and Staff Wellbeing"],["30-08-2024","Designing the Perfect Interior Lighting Scheme with LEDs"],["29-08-2024","Sustainable Lighting: How LEDs Contribute to Green Building Practices"],["27-08-2024","Case Study: LED Lighting Solutions for a Major Industrial Complex"]].map(x=><article key={x[1]}><small>{x[0]}</small><h2>{x[1]}</h2><p>Explore lighting ideas, applications and practical guidance from LunnArk.</p><a href="/blogs">Read More →</a></article>)}</div></section></Layout>;
if(path==="/patents") return <Layout title="Patents Registered"><section className="content-section"><div className="patent-grid">{[["LINIO CURVE","202341090359"],["ACRYLIC GLO","202441016840"],["HALOS","202441027214"],["WALL MOUNT","202441023400"]].map(x=><div className="patent-card" key={x[0]}><h2>{x[0]}</h2><p>Patent Pending · App. No: {x[1]}</p></div>)}</div></section></Layout>;
if(path==="/video_gallery") return <Layout title="Video Gallery"><section className="content-section"><div className="video-placeholder"><h2>LunnArk Video Gallery</h2><p>Project and product videos.</p></div></section></Layout>;
if(path==="/news-events"||path==="/news_events") return <Layout title="News & Events"><section className="prose-section"><h2>Innovation and Recognition</h2><p>LunnArk has been recognised as The Most Innovative Company for Technical & Decorative LED Lighting Solutions-2022 by BusinessMint.</p></section></Layout>;
if(path==="/terms") return <Layout title="Terms & Conditions"><section className="prose-section"><h2>General Terms & Conditions</h2><p>Use of this website and its content is subject to LunnArk terms and conditions.</p></section></Layout>;
if(path==="/privacy") return <Layout title="Privacy"><section className="prose-section"><h2>Privacy Policy</h2><p>LunnArk respects your privacy and uses submitted information to respond to enquiries and provide services.</p></section></Layout>;
if(path.startsWith("/blogs/")) return <Layout title={slug.slice(1).join(" ").replace(/-/g," ")}><section className="prose-section"><h2>LunnArk Blog</h2><p>Lighting design is about more than illumination. Explore ideas, applications and practical considerations for creating better spaces.</p></section></Layout>;
return <Layout title="LunnArk"><section className="content-section"><h2>Page</h2><p>This LunnArk section is being migrated locally.</p></section></Layout>;
}